document.addEventListener("DOMContentLoaded", function () {
  const tipButton = document.getElementById("tipButton");
  const tipDisplay = document.getElementById("tipDisplay");

  // Sample tips data in JSON format
  const tipsData = [
    "Take her out for a surprise or not surprise date night. Try a restaurant like Top hat, enjoy some drinks at LiquidPlanet, Dine at 5 on black, and end the night with a romantic movie.",
    "Write a heartfelt note expressing your love and appreciation.",
    "Surprise her with a thoughtful gesture that shows you care.",
    "Help with household chores without being asked, and make it a pleasant surprise.",
    "Plan a weekend getaway to a romantic destination and spend quality time together.",
    "Cook her favorite meal as a special surprise, complete with candles and a nicely set table.",
    "Create a personalized playlist of songs that hold special meaning for both of you.",
    "Take a dance class together to share a fun and intimate experience.",
    "Plan a picnic in a scenic location with her favorite foods and drinks.",
    "Organize a game night with board games or video games for a playful and entertaining evening.",
    "Write a list of reasons why you love her and share it with her as a sweet surprise.",
    "Surprise her with breakfast in bed on a lazy weekend morning.",
    "Take a scenic drive together and enjoy the beauty of nature.",
    "Create a DIY spa night at home with relaxing massages and pampering treatments.",
    "Plan a surprise visit to her favorite place or a location that holds sentimental value.",
    "Organize a photo album or scrapbook of your favorite memories together.",
    "Visit an art gallery or museum for a cultural and enriching experience.",
    "Plan a stargazing night with a cozy blanket and some hot cocoa.",
    "Take a class together, whether it's cooking, painting, or something you both enjoy.",
    "Surprise her with a bouquet of her favorite flowers.",
    "Create a scavenger hunt with clues leading to special moments in your relationship.",
    "Plan a movie marathon with all her favorite films and snacks.",
    "Write and perform a love song or poem dedicated to her.",
    "Go for a romantic walk under the moonlight and share your dreams and aspirations.",
    "Plan a surprise date to recreate your first date and reminisce about how you met.",
    "Take a day off to spend quality time together without any distractions.",
    "Surprise her with tickets to a concert or show featuring her favorite artist.",
    "Create a memory jar filled with notes about your favorite shared moments.",
    "Organize a surprise dinner party with close friends and family to celebrate your relationship.",
    "Visit a local farmers' market together and pick out fresh ingredients for a home-cooked meal.",
    "Take a spontaneous road trip to explore new places together.",
    "Surprise her with a custom piece of jewelry that holds sentimental value.",
    "Plan a weekend of outdoor activities, such as hiking, biking, or camping.",
    "Create a DIY project together, whether it's home decor or a personalized gift.",
    "Plan a romantic beach day with sun, sand, and a picnic.",
    "Surprise her with a book club featuring a novel you both can read and discuss.",
    "Write love letters to each other and exchange them as a surprise.",
    "Take a cooking class together to learn new recipes and techniques.",
    "Plan a surprise date night at home with a homemade dinner and a cozy movie marathon.",
    "Visit a local winery or brewery for a tasting experience.",
    "Surprise her with a weekend of pampering and relaxation at a spa.",
    "Take a hot air balloon ride for a breathtaking and romantic adventure.",
    "Create a playlist of songs that represent your relationship and share it with her.",
    "Plan a surprise visit to her favorite restaurant for a special dinner.",
    "Organize a themed date night based on a shared interest or favorite movie.",
    "Surprise her with a custom piece of artwork or a handmade gift.",
    "Plan a day of exploring a nearby city and discovering hidden gems.",
    "Write love notes and hide them in unexpected places for her to find throughout the day.",
    "Surprise her with a handwritten love poem or letter.",
    "Take a pottery or art class together for a creative and memorable experience.",
    "Plan a day of outdoor activities like hiking, biking, or a romantic nature walk.",
    "Create a surprise romantic dinner at home with candlelight and soft music.",
    "Surprise her with a framed photo of a special moment you shared together.",
    "Organize a virtual game night with friends for a fun and social evening.",
    "Plan a surprise visit to her workplace with her favorite snacks or lunch.",
    "Write down your favorite memories together on small cards and surprise her with them.",
    "Take a scenic train or boat ride together for a unique and relaxing experience.",
    "Organize a themed costume night at home for a playful and entertaining date.",
    "Surprise her with a personalized piece of jewelry that symbolizes your love.",
    "Plan a visit to a botanical garden or flower show for a romantic and colorful outing.",
    "Create a DIY candle-making night and make personalized candles together.",
    "Surprise her with a subscription to a magazine or service that aligns with her interests.",
    "Plan a surprise beach bonfire with marshmallows, chocolate, and a cozy blanket.",
    "Write a list of future goals and dreams you want to achieve together.",
    "Surprise her with tickets to a comedy show for a night filled with laughter.",
    "Take a scenic helicopter ride for an unforgettable and thrilling experience.",
    "Organize a surprise movie night under the stars with a projector and blankets.",
    "Plan a surprise visit to a zoo or animal sanctuary for a day of cute and memorable moments.",
    "Create a scrapbook of your relationship milestones and surprises.",
    "Surprise her with a framed map marking the locations that are significant to your relationship.",
    "Organize a surprise virtual party with friends and family to celebrate your love.",
    "Plan a surprise breakfast date at a cozy cafe with her favorite treats.",
    "Surprise her with a customized piece of clothing or accessory that reflects her style.",
    "Take a dance or fitness class together for a fun and active date night.",
    "Plan a surprise hike to a beautiful viewpoint and enjoy a picnic at the top.",
    "Write a list of qualities you admire about her and share it as a surprise affirmation.",
    "Surprise her with a handwritten love coupon book for special favors or treats.",
    "Plan a surprise karaoke night at home with her favorite songs and snacks.",
    "Organize a surprise visit to a winery for a tasting tour and scenic views.",
    "Create a surprise DIY home spa day with pampering treatments and relaxation.",
    "Surprise her with a custom piece of art or a portrait that captures your love.",
    "Plan a surprise visit to a botanical garden or arboretum for a serene and romantic atmosphere.",
    "Take a hot air balloon or helicopter ride for a breathtaking and romantic adventure.",
    "Write a series of love letters and hide them in different places for her to discover throughout the week.",
    "Surprise her with a personalized star map depicting the night sky on a significant date in your relationship.",
    "Organize a surprise virtual cooking class and prepare a special meal together from the comfort of your homes.",
    "Order her favorite meal",
    "Cuddle when she is tired ",
    "Have a pizza ready when you know she has a tedious day at work ",
    "Give her nice back rub",
    "Have a Shower with her",
    "Make Time for Time With Your Wife",
    "Tell Her How Much She Means to You.",
    "Become the Best Version of Yourself.",
  ];

  // Function to generate a random tip
  function getRandomTip() {
    const randomIndex = Math.floor(Math.random() * tipsData.length);
    return tipsData[randomIndex];
  }

  // Event listener for button click
  tipButton.addEventListener("click", function () {
    const randomTip = getRandomTip();
    tipDisplay.textContent = randomTip;
  });
});
